### PR TITLE
Implement hal standard

### PR DESCRIPTION
**Pull request by ELC**
This is a stacked PR, do not review before merging #47

### CODE REVIEW

**Comment by jtc42** [comment]
https://github.com/jtc42/fastapi-hypermodel/pull/47 merged. Will hold off here until rebased (or merged or however you want to manage it), and tests are passing. Thanks again!

**Comment by ELC** [comment]
@jtc42 Ready for review

Some of the changes in this PR include:
- Add support for CURIEs
- Add missing fields based on the HAL Specification (e.g. profile, hreflang, deprecation)
- Fix some typos in the field names to match the standard (e.g. template to template**d**)
- Add new Response type `HALResponse` that adds the media type `application/hal+json`
- Add validation of the response:
    - Check if links are valid
    - Check if links include a self link
    - Check if CURIES are resolvable
    - Recursive check embedded resources
- Add a new class HALHyperModel which detects another HALHyperModels and automatically adds them to the _embedded property
- Simplify types by using aliases
- Rename __build_hypermedia__ to __call__ for a more pythonic approach
- Use protocol types (Mapping and Sequence) instead of concrete types
- Add unit tests where needed
- Make examples more similar by adapting the data module
- Use more strict checks with ruff by checking the test folder as well
- Add types to the data module by using TypedDict

**Comment by jtc42** [comment]
Thanks, I'll go through this asap.

**Comment by jtc42** [comment]
Sorry for the delay getting back to you on this. Generally this looks great, though I would like to just double check one thing.

The way I'd always kind of intended this to work was for there to be a single `HyperModel` class which can be used with any of the hypermedia field classes. This is why it was implemented in the way that it was.

I see here though that the PR introduces a separate model class just for HAL fields.

If there's a way we could rejig things a bit so the single `HyperModel` class can handle both (I guess any ideally) field types, that would be far more fitting with how I'd ideally like this to work.

It may not be possible, or possible but really messy, in which case fine but I'd love if we could look into options at least.

**Comment by ELC** [comment]
@jtc42 Regarding the class `HalHyperModel` ([https://github.com/jtc42/fastapi-hypermodel/blob/b6daf9d48d413ea225befd570c79af88fad675c4/fastapi_hypermodel/hal.py#L125-L171](code)). I believe using inheritance is the cleanest way in this case at least given the following assumptions.

 HAL establish that all other hypermodels should be in a `_embedded` property, and there is a validator (`add_hypermodels_to_embedded`) that takes care of this automatically. The rationale is that the user does not need to know that this is actually happening, the process of grouping all the hypermodels into a `_embedded` property is transparent and happens under the hood. However that logic is only applicable for HAL, any other hypermedia model may or may not use a similar logic, [SIREN](https://github.com/kevinswiber/siren) groups the hypermodels under `entities` but in a list rather than mapping.

Having all of this logic in the parent class will make the code really coupled and hard to maintain, i.e. we will end up with a lot of assumptions and if/elif logic. Another alternative may be to explore metaclasses with arguments and then declare the models like:

```python
class C(metaclass=HyperModel, hypermedia_format=HypermediaFormat.HAL):
  pass
```

But this last approach is not widely used in the community and will also make things harder to understand for anyone wanting to contribute and extend the code.

---

Inevitably some hypermedia formats present themselves with not only "field logic" but also "global logic", if all there was was "field logic", then it would be possible to use a single `HyperModel` class, but we need subclasses to handle the "global logic". Another much more tricky aspect of HAL is cURIes, which were non-trivial to implement and validate.

I am also implementing SIREN in [a separate PR](https://github.com/jtc42/fastapi-hypermodel/pull/49/) and used this same approach of especialized HyperModel subclasses, in the case of SIREN, the [logic is much more complicated](https://github.com/jtc42/fastapi-hypermodel/blob/5eed528de95ca221e9673e5a086e04218e028586/fastapi_hypermodel/siren.py#L335-L460). Combining SIREN's, HAL's and future format's "global logic" into the HyperModel would make things much harder in the long term. 

The main advantage for this is that one can play around with a new subclass of HyperModel without fearing breaking anything else, having everything in the HyperModel class introducing coupling between the formats which may or may not make sense.

Waiting to see your thoughts on this

**Comment by jtc42** [comment]
Yeah ok that reasoning all makes sense to me. I'm happy with that, and I think it's good that it's documented here.

On that, would you be happy updating the docs directory too, just to include usage (and output examples) of any new classes you add? Either in the "Advanced" section, or maybe a new one for alternative formats (include HAL and SIREN once that's merged perhaps?)

Once that's done I think this is basically good to go. There's enough changes I'd like to do one last pass through it just to check I fully understand everything that has change.

Thanks.

**Comment by ELC** [comment]
@jtc42 Happy to clarify any time

Would you mind merging this PR first, then I will wrap up the Siren one and after that I will create a follow up PR to iron out any details (e.g. making sure same behaviour is tested in all formats) and update the docs?

I prefer to work in smaller PRs, after everything has been merged, we can publish a new release to PyPI

**Pull request merged**
