### PR TITLE
Adding stricter quality checks

### PR DESCRIPTION
**Pull request by ELC**

### CODE REVIEW

**Comment by jtc42** [comment]
Do you think there's much value in keeping pylint around at all, or could that be entirely replaced by ruff do you think?

**Comment by ELC** [comment]
Yes and no, I would totally replace PyLint with Ruff if it were a drop-in replacement but for that Ruff has to close [this issue](http://github.com/astral-sh/ruff/issues/970).

There are many checks that are now currently only done by PyLint, such as the similarity and complexity ones

Ruff already replaced Flake8, Black and Isort, so it is a matter of time

**Comment by ELC** [comment]
@jtc42 Please feel free to review and leave comments

**Comment by jtc42** [comment]
Thanks! I'll go through this properly in the new year but by and large this looks fine. I'm a little bit wary of the number of custom config options set for ruff and pylint, but if there's reasons for it all then fair enough. Just need to consider if there's a maintenance overhead introduced by the configs. _Hopefully_ at some point we can just replace it all with a standard "vanilla" ruff config.

**Comment by ELC** [comment]
Conflicts were fixed now 

Sounds good, I am working on a stacked PR to address other type of changes. 

Regarding the custom config options, ruff has a pretty basic default config, so the ruff configs just makes sures it fully replaces flake8 and most of the widely used plugins. 

As per Pylint, the defaults are usually not ideal so the custom configs are to make the maintainer life easier.

As the mantainability effort, it is usually huge when there is a large codebase already, for incremental changes, it is usually straightforward, ruff also fixes the issues if possible and pylint issues are pretty descriptive. Depends on how used to one  is to the code standard Pylint tries to push, but I consider that a prorather than a con.

Take your time and Happy New Year

**Pull request merged**
