### PR TITLE
Implement the SIREN Hypermedia Format - Closes #42

### LINKED ISSUE #42: Siren support?
I would like to use HATEOAS with Hypermedia Maturity Level 2's Siren

Is the repo open for contributions and PRs?

### PR DESCRIPTION
**Pull request by ELC**
This PR adds support for [SIREN](https://github.com/kevinswiber/siren), it is stacked on top of [HAL's PR](https://github.com/jtc42/fastapi-hypermodel/pull/48). Merge #48 before reviewing this.

Why Siren?

So far the repo supports URLFor and HAL. URLFor provides simple URI hyperlinks whereas HAL supports more complex relationships. Even though the current implementation of HALFor auto-detects methods, that it is not part of the HAL Standard, and having method information without information about the parameters is not useful. Siren provides links (same principle as HAL's) but it also adds actions which model the different operations that can be run on a given resource, detailing not only the URI but also de method and the fields needed.

Features added:

- SIREN Hypermedia format is now supported using new project structure
- Add SIREN Example using the same data as the URLFor's and HAL's
- Add official jsonchema validation to SIREN responses
- Fix small bug in LinkSet
- Remove HALFor's method and description support as it is not part of the standard and that feature could be now used by leveraging SIREN

### CODE REVIEW

**Comment by ELC** [comment]
@jtc42 Please feel free to review after merging #48

**Comment by jtc42** [comment]
Could you please rebase so it's clearer what's actually changed between this and the recently merged HAL branch?

More generally, I think once this is merged I'll do a new major release. While there's likely no breaking changes, there's enough changed "under the hood" that I'd prefer to clearly delineate it with a major release.

Given my time constraints and move away from using (and so developing) this library, I do wonder if it would make more sense to either transfer ownership, or at least give you full access, to you. I'd like to know your thoughts on this though. If I'm honest, this library was originally cobbled together to serve a really specific purpose for my work, but hasn't been used in that project for a while now. I still think it's _useful_, and I'm really glad others are continuing to use it, but if I'm being honest I can't see myself keeping up with it enough to do it justice.

An extra aside, after merging the HAL branch tests on main are now failing (probably should have put a branch protection rule in place to block merges that aren't up to date with main, but whatever). If you rebase this branch anyway though we can hopefully get that sorted here.

**Comment by ELC** [comment]
@jtc42 I updated the branch and now the results can be seen independently of the previously merged PR.

I'd happily take ownership of the library if you consider that as an option. I am planning on heavily using it and can maintain it at least for the foreseeable future.

I am currently working on the last PR of this series, focusing on avoid repeating code, make sure the code is easier to extend, documentation and overall structure. That is reflected in PR #51. I believe that will be ready sometime today and after that it will deefinitely justify a major release update.

**Comment by ELC** [comment]
@jtc42 This should be good to merge now

Merging this will close #42

**Pull request merged**
