### PR TITLE
Pydantic 2: Make the tests run

### PR DESCRIPTION
**Pull request by christoe**
We're looking to upgrade to pydantic 2, but are currently blocked by fastapi-hypermodel and some other libraries. I took the liberty to help you out with your branch and get it running to speed things up (saw your comment in #32).

Tests now pass and I think things are in order, but I'm not an pydantic internals expert. Please have a look and get in touch if you want to discuss anything.

### CODE REVIEW

**Comment by jtc42** [comment]
This is fantastic, thank you so much! I've had a quick look and everything looks fine (better than fine to be honest).

I'll do a deeper dive into it tomorrow but I really can't see there being any issues.

**NB:** Tests are failing in GitHub Actions but that's a poetry issue. I'll try and get it fixed in `main` shortly so you can update the fork and that should kick everything into working again.

**Comment by jtc42** [comment]
When you get chance, could you merge in the latest changes from `main` (see https://github.com/jtc42/fastapi-hypermodel/pull/34) and the tests should start passing in the CI.

Issue seems to have just been Poetry complaining about Python 3.7, which is EOL anyway.

**Comment by christoe** [comment]
I rebased from master to get your fixes in. I've also integrated the new version in the software that we're writing to get some more test coverage - which led me to find a few more issues that I've now fixed together with the pylint/black issues. Could you approve the workflow to see if the build goes through this time?

**Comment by jtc42** [comment]
Workflow approved (I'm looking to see if there's a way I can auto-approve for this PR). 

It's failing on 3.8 but I think that's just because we need to still use `typing.Dict` instead of `dict` for type hints for the time being. Should be a really quick fix.

**Comment by jtc42** [comment]
@christoe Given how extensive these changes are, and the time you've spent on them, are you happy to be listed as a co-author in the library? It seems to me inappropriate for me to still be listed as the sole author given how much you've contributed to the code.

**Comment by christoe** [comment]
@jtc42: I'll let that be up to you. It's still your original idea and I've only tried to adapt the code to support our use case.

I've also tried fixing the mypy issue with dict vs. typing.Dict.

**Pull request merged**
